### ISSUE TITLE
useSetup.mel删除整个文件改成删除病毒所在的那一行代码

### ISSUE THREAD

**Issue by ONETOWCN** [loonghao/maya_umbrella#19]
有个朋友反馈，有的人的useSetup.mel里面是装了插件的，所以能不能精准定位到python base64那一行删除，而不是整个useSetup.mel删除呢，省去重装插件的麻烦

**Comment by loonghao** [comment]
@ONETOWCN 方便给一个相关类似的userSetup.mel么？我们好添加到单元测试中

**Comment by ONETOWCN** [comment]
[userSetup.mel.json](https://github.com/loonghao/maya_umbrella/files/15217547/userSetup.mel.json)
因为不支持mel格式，直接在后面加了.json。到时候删掉后缀名就行。
这是一个带绑定插件，同时又感染病毒的userSetup.mel，希望能帮到您

**Comment by loonghao** [comment]
感谢，当前我已经在更新代码去支持这个了。现在遇到的卡点是，遇到一些包含中文内容的 userSetup.py 和 userSetup.mel 

在py2 py3 上面的兼容不太好弄。我可以先考虑出一个版本先兼容 不含unicode的版本。

**Comment by loonghao** [comment]
https://github.com/loonghao/maya_umbrella/releases/tag/v0.5.0
已经解决了这个问题

**Comment by ONETOWCN** [comment]
niubi
