### ISSUE TITLE
希望添加命令行批量处理的功能

### ISSUE THREAD

**Issue by uncleschen** [loonghao/maya_umbrella#8]
**Describe the bug**
指定列表文件的批处理功能

**Expected behavior**
是否允许我传入txt文件路径，txt文件路径中存在着我需要查杀的maya文件路径，一行一个，每一行逐步清理下来。

批处理是否还可以增加选项，可以让我选择是否需要清理完成后保存，还是在原maya文件边上创建一个backup文件夹放入其中，清理当前保存。
1. 什么都不做
2. 保存当前
3. 备份一份在原maya文件边上的backup文件夹内，再保存当前

**Comment by loonghao** [comment]
好的，晚上添加

**Comment by loonghao** [comment]
已经支持
